### ISSUE TITLE
[SI - PBI6] melihat beranda dan katalog

### ISSUE THREAD

**Issue by ahmadsidikrofi** [SI-RPL-2023/SI4406_KEL5_READTERACY#8]
Sebagai seorang member saya ingin melihat beranda dan katalog maka saya harus mengakses website
![Home](https://user-images.githubusercontent.com/88192138/227868349-4eb7ab00-a559-4476-9dab-9606116d7f34.png)

**Comment by ahmadsidikrofi** [comment]
ini gimana?

**Comment by najmaasr** [comment]
ya begitu
